name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: lean action
        uses: leanprover/lean-action@f061402b660e0c34644504b324e830f2991d4865 # v1.6.1
        with:
          build-args: "--log-level=warning"
